microsoft/malmo

CMakeLists.txt
Malmo/samples/Python_examples/craft_work.py
Minecraft/src/main/java/com/microsoft/Malmo/MalmoMod.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/MazeDecoratorImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromFullInventoryImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForCollectingItemImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForDiscardingItemImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForItemBase.java
Minecraft/src/main/java/com/microsoft/Malmo/Utils/BlockDrawingHelper.java
Minecraft/src/main/java/com/microsoft/Malmo/Utils/CraftingHelper.java
Schemas/Mission.xsd
Schemas/MissionEnded.xsd
Schemas/MissionHandlers.xsd
Schemas/MissionInit.xsd
Schemas/Types.xsd
changelog.txt

Crafting refinements

---

Malmo/samples/Python_examples/reward_for_items_test.py
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromNearbyEntitiesImplementation.java
Schemas/Mission.xsd
Schemas/MissionHandlers.xsd
changelog.txt

Added observation from nearby entities.

---

Minecraft/src/main/java/com/microsoft/Malmo/MalmoMod.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/DiscreteMovementCommandsImplementation.java
Schemas/MissionHandlers.xsd
changelog.txt

Added support for `use` and  `attack` commands in discrete mode.

---

Malmo/samples/Java_examples/JavaExamples_run_mission.java
Malmo/src/JavaWrapper/CMakeLists.txt
Malmo/test/JavaTests/test_ALE_built.java
Malmo/test/JavaTests/test_agent_host.java
Malmo/test/JavaTests/test_argument_parser.java
Malmo/test/JavaTests/test_mission.java
Malmo/test/JavaTests/test_parameter_set.java
Malmo/test/JavaTests/test_wrapping.java

Javapackage

---

CMakeLists.txt
Malmo/src/ALEAgentHost.cpp
Malmo/src/ALEAgentHost.h
Malmo/src/TimestampedReward.cpp
Malmo/src/TimestampedReward.h
Minecraft/src/main/java/com/microsoft/Malmo/MalmoMod.java

Closes #252 - amounts to roughly a 20x speedup in using the ALE.

Circumnavigated costly xml wrangling

---

Malmo/samples/Python_examples/craft_work.py
Minecraft/src/main/java/com/microsoft/Malmo/Client/MalmoModClient.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/SimpleCraftCommandsImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/Utils/CraftingHelper.java
Minecraft/src/main/resources/assets/MalmoMod/lang/en_US.lang
changelog.txt

Added smelting recipes to simple crafting.

---

Minecraft/src/main/java/com/microsoft/Malmo/EpisodeEventWrapper.java
Minecraft/src/main/java/com/microsoft/Malmo/Server/ServerStateMachine.java
Minecraft/src/main/java/com/microsoft/Malmo/StateEpisode.java
changelog.txt

Made spawn control more sensible and less leaky.

---

Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/DiscreteMovementCommandsImplementation.java
changelog.txt

Use discretion

---

Malmo/samples/Python_examples/CMakeLists.txt
Malmo/samples/Python_examples/mission_quit_command_example.py
Malmo/src/MissionSpec.cpp
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/MissionBehaviour.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/MissionQuitCommandsImplementation.java
Schemas/Mission.xsd
Schemas/MissionHandlers.xsd

Closes #170, based off pr #285 by @bengioe

Mission quit command

---

Malmo/samples/Python_examples/CMakeLists.txt
Malmo/samples/Python_examples/two_diggers.py
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/DiscreteMovementCommandsImplementation.java

Fix: use and attack in discrete movement multi-agent missions

---

Malmo/src/AgentHost.cpp

Fixes #299.
Thanks to @salaniz for highlighting this issue.

Fix: calling Xerces Initialize and Terminate

---

Minecraft/src/main/java/com/microsoft/Malmo/Client/ClientStateMachine.java

Fix: missions now checked for equality in multi-agent missions.

---

Minecraft/src/main/java/com/microsoft/Malmo/Client/ClientStateMachine.java

When a multi-agent mission is searching for a server and encounters one with the same mission and the same experiment ID.
Fixes #14

Fix: give MALMOERROR on multi-agent mission with matching mission and experiment ID

---

Malmo/samples/Python_examples/two_diggers.py
Minecraft/src/main/java/com/microsoft/Malmo/MalmoMod.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/DiscreteMovementCommandsImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForCollectingItemImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForDiscardingItemImplementation.java
changelog.txt

Fixes #297. Fixes #303.
Also extended two_diggers.py to test the continuous-action rewards.

Attack and use commands now trigger rewards

---

Minecraft/src/main/java/com/microsoft/Malmo/Server/ServerStateMachine.java
Minecraft/src/main/java/com/microsoft/Malmo/Utils/EnvironmentHelper.java
changelog.txt

Weather now periodically reset during mission run.

---

Malmo/samples/Python_examples/drawing_test.py
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromGridImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/Utils/JSONWorldDataHelper.java
Schemas/MissionHandlers.xsd
changelog.txt

New attribute `absoluteCoords` with default = false.
Closes #293

ObservationFromGrid can now also return a fixed-location grid.

---

Minecraft/src/main/java/com/microsoft/Malmo/Utils/BlockDrawingHelper.java
Schemas/MissionHandlers.xsd
Schemas/Types.xsd
changelog.txt

Draw entities

---

Malmo/samples/Python_examples/CMakeLists.txt
Malmo/samples/Python_examples/cart_test.py
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ClassroomDecoratorImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/DrawingDecoratorImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/MazeDecoratorImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/Utils/BlockDrawingHelper.java
Minecraft/src/main/java/com/microsoft/Malmo/Utils/MinecraftTypeHelper.java
Schemas/Types.xsd
changelog.txt

Drawing refactor

---

Minecraft/src/main/java/com/microsoft/Malmo/Client/ClientStateMachine.java

Force-load the initial chunk to help with block sync issues.

---

Malmo/samples/Python_examples/CMakeLists.txt
Malmo/samples/Python_examples/file_test.py
Minecraft/src/main/java/com/microsoft/Malmo/Client/ClientStateMachine.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/FileWorldGeneratorImplementation.java
changelog.txt

File worlds

---

Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromRayImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/Utils/MinecraftTypeHelper.java
Schemas/MissionHandlers.xsd
changelog.txt

Rays of hope

---

Minecraft/src/main/java/com/microsoft/Malmo/MalmoMod.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForCollectingItemImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForDiscardingItemImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForItemBase.java

Item reward fix

---

Minecraft/src/main/java/com/microsoft/Malmo/Client/ClientStateMachine.java

Garbage collected each time the client reaches the dormant state.

---

Malmo/samples/Python_examples/CMakeLists.txt
Malmo/samples/Python_examples/chunk_test.py
Malmo/samples/Python_examples/robust_frames.py
Malmo/samples/Python_examples/teleport_test.py
Minecraft/src/main/java/com/microsoft/Malmo/Client/ClientStateMachine.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/AbsoluteMovementCommandsImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/Server/ServerStateMachine.java
changelog.txt

Questions in a world of blue

---

Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromFullStatsImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/Utils/JSONWorldDataHelper.java
Schemas/MissionHandlers.xsd
changelog.txt

Time please gentlemen

---

Minecraft/src/main/java/com/microsoft/Malmo/Server/ServerStateMachine.java
changelog.txt

Remove grace period of invulnerability at start of mission

---

Malmo/src/MissionRecord.cpp
Malmo/src/MissionRecord.h
changelog.txt

Changed file naming in tarballs.

---

Malmo/samples/Python_examples/CMakeLists.txt
Malmo/samples/Python_examples/build_test.py
Minecraft/src/main/java/com/microsoft/Malmo/Client/ClientStateMachine.java
Minecraft/src/main/java/com/microsoft/Malmo/MalmoMod.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlerInterfaces/IWorldDecorator.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/BuildBattleDecoratorImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ClassroomDecoratorImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/DiscreteMovementCommandsImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/DrawingDecoratorImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/MazeDecoratorImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/MissionBehaviour.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/MultidimensionalReward.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromSubgoalPositionListImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForStructureCopyingImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/SnakeDecoratorImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/WorldFromComposite.java
Minecraft/src/main/java/com/microsoft/Malmo/Server/ServerStateMachine.java
Schemas/Mission.xsd
Schemas/MissionHandlers.xsd
changelog.txt

Build battles

---

CMakeLists.txt
Malmo/samples/Python_examples/CMakeLists.txt
Malmo/samples/Python_examples/discrete_3d_test.py
Minecraft/src/main/java/com/microsoft/Malmo/Client/ClientStateMachine.java
Minecraft/src/main/java/com/microsoft/Malmo/MalmoMod.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/DiscreteMovementCommandsImplementation.java
Schemas/Mission.xsd
Schemas/MissionEnded.xsd
Schemas/MissionHandlers.xsd
Schemas/MissionInit.xsd
Schemas/Types.xsd
changelog.txt

Discrete expansion

---

Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForTimeTakenImplementation.java
Schemas/Mission.xsd
Schemas/MissionHandlers.xsd
changelog.txt

Timely rewards

---

.travis/ci_ubuntu14.04.sh
Minecraft/gradle/wrapper/gradle-wrapper.properties

Travis CI fix

---

Malmo/samples/Python_examples/CMakeLists.txt
Malmo/samples/Python_examples/agent_visibility_test.py
Malmo/samples/Python_examples/multi_agent_test.py
Minecraft/launch_minecraft_in_background.py
Minecraft/src/main/java/com/microsoft/Malmo/Client/ClientStateMachine.java

The invisible man

---

CMakeLists.txt
Malmo/samples/Python_examples/CMakeLists.txt
Malmo/samples/Python_examples/turn_based_test.py
Malmo/src/AgentHost.cpp
Malmo/src/AgentHost.h
Malmo/src/CSharpWrapper/MalmoNETNative.i
Malmo/src/JavaWrapper/MalmoJava.i
Malmo/src/LuaWrapper/lua_module.cpp
Malmo/src/PythonWrapper/python_module.cpp
Minecraft/src/main/java/com/microsoft/Malmo/Client/ClientStateMachine.java
Minecraft/src/main/java/com/microsoft/Malmo/MalmoMod.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/CommandBase.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/CommandGroup.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/HandlerBase.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/MissionBehaviour.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromComposite.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromSubgoalPositionListImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromTurnSchedulerImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/QuitFromComposite.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardGroup.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/TurnBasedCommandsImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/Server/ServerStateMachine.java
Schemas/Mission.xsd
Schemas/MissionEnded.xsd
Schemas/MissionHandlers.xsd
Schemas/MissionInit.xsd
Schemas/Types.xsd
changelog.txt

Turn scheduler

---

doc/build_linux.md

Fix build linux md

---

CMakeLists.txt
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/AgentQuitFromCatchingMobImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardBase.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/RewardForCatchingMobImplementation.java
Schemas/Mission.xsd
Schemas/MissionEnded.xsd
Schemas/MissionHandlers.xsd
Schemas/MissionInit.xsd
Schemas/Types.xsd
changelog.txt

Catch the pig

---

Minecraft/src/main/java/com/microsoft/Malmo/Client/ClientStateMachine.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromNearbyEntitiesImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromRayImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/OverclockingClassTransformer.java
Minecraft/src/main/java/com/microsoft/Malmo/Utils/BlockDrawingHelper.java
Schemas/MissionHandlers.xsd

Yaw so vain

---

Malmo/samples/Python_examples/cart_test.py
Malmo/samples/Python_examples/mob_fun.py
Malmo/samples/Python_examples/multi_agent_test.py
Malmo/samples/Python_examples/reward_for_items_test.py
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromNearbyEntitiesImplementation.java

I added a simple check to add life to the observations from living entities similar to the check for item stack specific values.
I'm working on a project with player/entity interaction and couldn't find any other way to get the life of an entity.

Added life to observations of living entities.

---

Malmo/samples/CSharp_examples/Program.cs
Malmo/samples/Java_examples/JavaExamples_run_mission.java
Malmo/samples/Lua_examples/run_mission.lua
Malmo/samples/Python_examples/CMakeLists.txt
Malmo/samples/Python_examples/MultiMaze.py
Malmo/samples/Python_examples/agent_visibility_test.py
Malmo/samples/Python_examples/multi_agent_test.py
Malmo/samples/Python_examples/team_reward_test.py
Malmo/samples/Python_examples/turn_based_test.py
Malmo/samples/Python_examples/two_diggers.py
Malmo/src/AgentHost.cpp
Malmo/src/AgentHost.h
Malmo/src/CSharpWrapper/MalmoNETNative.i
Malmo/src/JavaWrapper/MalmoJava.i
Malmo/src/Logger.cpp
Malmo/src/Logger.h
Malmo/src/LuaWrapper/lua_module.cpp
Malmo/src/PythonWrapper/python_module.cpp
Minecraft/launchClient.sh
Minecraft/launch_minecraft_in_background.py
Minecraft/src/main/java/com/microsoft/Malmo/Client/ClientStateMachine.java
Minecraft/src/main/java/com/microsoft/Malmo/MalmoMod.java
Minecraft/src/main/java/com/microsoft/Malmo/Utils/TCPSocket.java
Minecraft/src/main/java/com/microsoft/Malmo/Utils/TCPUtils.java

Next time I say something like "I'll just quickly add some custom exception handling, it shouldn't be hard", please draw my attention to this PR, and remind me how many different languages we're currently supporting...

Multi hardening

---

CMakeLists.txt
Malmo/samples/Python_examples/CMakeLists.txt
Malmo/samples/Python_examples/inventory_test.py
Minecraft/src/main/java/com/microsoft/Malmo/Client/MalmoModClient.java
Minecraft/src/main/java/com/microsoft/Malmo/MalmoMod.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/InventoryCommandsImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromFullInventoryImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromFullStatsImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromGridImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromHotBarImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromNearbyEntitiesImplementation.java
Minecraft/src/main/java/com/microsoft/Malmo/MissionHandlers/ObservationFromServer.java
Minecraft/src/main/java/com/microsoft/Malmo/Server/ServerStateMachine.java
Minecraft/src/main/java/com/microsoft/Malmo/Utils/BlockDrawingHelper.java
Minecraft/src/main/java/com/microsoft/Malmo/Utils/MinecraftTypeHelper.java
Schemas/Mission.xsd
Schemas/MissionEnded.xsd
Schemas/MissionHandlers.xsd
Schemas/MissionInit.xsd
Schemas/Types.xsd

Chest expansion

---

scripts/malmo_install.ps1

To install mesa, use the flag -headless

Optional mesa install

---

scripts/docker/build_centos7_python3.dockerfile
scripts/docker/build_debian8_python3.dockerfile
scripts/docker/build_debian9_python3.dockerfile
scripts/docker/build_ubuntu1604_python3.dockerfile
scripts/docker/build_ubuntu1804_python3.dockerfile

matplot latest (3.x)  does not work with Python 3.4

remove entry point - scripted in k8 yaml

---

MalmoEnv/malmoenv/comms.py
MalmoEnv/malmoenv/core.py

Reties were on created socket
Last change to step broke single agent

malmoenv bugs

---

MalmoEnv/malmoenv/core.py
scripts/malmo_build.ps1

Issue: Link used to download Doxygen in malmo_build.ps1 is down #799

Doxygen link

---

CMakeLists.txt
MalmoEnv/README.md

Resolves #812.
Also add missing ` in MalmoEnv/README.md

Implement better Boost::Python finding routine in CMake

---

doc/install_macosx.md

https://github.com/Homebrew/homebrew-cask-versions/issues/7253

Update to available version of JDK8

---

MalmoEnv/proxyenv/__init__.py
MalmoEnv/proxyenv/action_utils.py
MalmoEnv/proxyenv/client.py
MalmoEnv/proxyenv/comms.py
MalmoEnv/proxyenv/malmo_proxyenv_client.py
MalmoEnv/proxyenv/malmo_proxyenv_serv.py
MalmoEnv/proxyenv/malmoenvwrap.py
MalmoEnv/proxyenv/minerl_proxyenv_client.py
MalmoEnv/proxyenv/minerl_proxyenv_serv.py
MalmoEnv/proxyenv/server.py

Useful Python module for remoting minerl or proxying malmoenv (or any other open ai gym enviromnent) over a network /  machine boundary.

add proxyenv sub module
